language: go
go:
- '1.5'
sudo: required
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO="jsloyer/go-hello-world"
  - secure: e+Ogck0CVYZmwD12DAftt4u4a7z4FqWpRkuVMFOMEePEmk+sj1CVK3WSfqe0/VQX6Nb8/Wxwx3ILxxQmUW+76+CE5II+YMkyyRmIfK7GVUDWrbWBHw+HW+sOl2iYSSYdTh9MDzcp5LoyM0VH/QxrJNDNQxcdHr5zvnJ7GTXiA50WjX+InmGjSE1DqnG4PUUAYq9CDscZgNDHOQ8qoUTMocwhmFk2YWGH1mY3JDpuy+GopgptuXTx6JX8752rADiiyEWxvleGmfzpg5HDHTvFG/Dz/aUi5YnU2jogrq6lbz+eguRCDF2fKHBjOM/I9UhEtAxP3G6uodXOc3F12zk+79WdTM5uw9HGhZovaCfl++QPk2NrjMpgZM3C7rVPcpYcEdKP4JQHz0IPBuBcKrJNGfVab+3Jt/515CfG1mjBOQnGIaMx/cz0jNYWtJp1b0Y/thc3gZrgWA8DWfzOxtxAze1KE6+k+Nzxt3ETGGGgVaGdswxwHy5thilBBPxQ8ioXkLFzDX9jxkz3P7m+NIRrOA+AJUv/skcbmggBG5IVcvAzZFaMtzsMoGWEIsAkIVM5gajs9m6pJj6exIMueDjUYmk8tFECPgBLx+MHNziQ7cYtkYcSmY5u+6mvfV+kKNXPRDC6VsEynDtyqhwURlJWF/8LEl6GNf+whRHJ1jkipRE=
  - secure: GNlTjtSvpqQr9mq2OI3lega3+NKK3IigImFAlOPl5aJXbO78Mrv2Ak0Z7WqDBK1a2nkC1nTGWfgnZtWchi70m7QOxNSkEwlnUhlKfgGBT6VslddsOrU0rQ8CImdrlRPPdPzIu8ZbNL9mqOnSv/Plxbo/99MT9PWbT8TiztEDPTOPb2Gpn+rjVCVXXyvfMWZuYCtrYH0EjklEyN4veR3kBJfbGniwrjd6FXMQ+173uQKX7RIpmSkPyCP0BGRJk1qOeK2gIxbanDQ4nqH6MjiDZV6qYI2IQKZuoujpEuqjT4ZZA6HWQ5Lg5aIV/f873ovhoWaYn7yl5kE6UPVTjyM3QHa4aFr+jR50zYEW47RfIFQlDRBq3jNMK+UtPznh39rePt29WqRA3Bf/ZYG6bW98/CNRGz6bZ90KmL7mz+ftOr7Vp9wsPW+NoLM+kY3DzxS820oC42YxfE45WyLBs7xazQlZUZokDRvk5nVOB5pFUUtrsV5ltYrKPpCeFxNeYaAugYHR+EoTQZmYq/Cn3Es9vs02ZMDxQ4aUXk1umXKHuitc2AAbcQc5Kpjb1FwP48JzPDiM+ngK/ghjbZx9qVGJ2LsjZTcqwYxh14HAFcxPOZDqZtoztqw8uRTCAbcDC+AWIwFS6o7ixpc6zA3NFgzJpVXh6AKJhzjopghOi8re2yM=
  - secure: WZEoK51b2YXFK5cH/0VRl9xU0yhrQR7Qm5pMWyu20ZvtJNP+O5DVL1uE4RxsDTzF5JJ8LSZO83bk7S/LUgnCCHita6j8ECgTeqmL+2753xEclD/g/QWxbSGpCyw+dT0bWUq/1hED6PVeRE07f6OND67BdnQdT5JzlCbADNenDdMWvwvEBbRBQU5lRbHWbEryhU0x7BksVjdlyk1qbXgJz6i4Td3oORnG/THfYBWAiidgQWK86ncXncg0swm8bLIqTZoMS6Ha++znIFNm2kg0ap8pVBg6d0DSFWsSrwxiW3YAz9kBcSXqN23xQNBx1vjBlJ7PRoSUiwXdPOYmMthlSzepG+DhDPWkbWfH3WzGuwpJ2DMP/kKMIgRGC2iifNdrwO5QJGCtspqlC7IE11tdbItW5TZVE7XEk3AanHgF0WOSOFAXgHJ/jNHIuxyDDpdkM2ktX1jefPkpDL0OUc9HRdBB4TTMnwttv7M73ZA0L39f1HjN1za7LFsvd+NegknFiMmouvb9NUEI6fKpctdlEF80ZhnPJ2sg1vf6/6cL4qAywIdcjnhxZkHsvBuzsSSJiHCgruWBGfe/9YE4vtyLY5GpalBmm3GvaqB7Hi5hv4xz5vEJGu5upZ/EnvAFV7v16U/s/XZgNwiHAeuIzENZyye/48iIrnc0iZSOyowPKxQ=
before_install:
- docker build -t $REPO:$COMMIT .
- docker run -d --name gohelloworld $REPO:$COMMIT
script:
- docker ps | grep -q gohelloworld
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
